FROM php:8.2-cli

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libzip-dev \
    libsqlite3-dev \
    libbrotli-dev \
    libssl-dev \
    && docker-php-ext-install zip pcntl pdo pdo_sqlite \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && yes "" | pecl install swoole \
    && docker-php-ext-enable swoole \
    && rm -rf /var/lib/apt/lists/*

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www
